### ISSUE TITLE
ImageTiledLayer is sealed class ? can I extends ?

### ISSUE THREAD

**Issue by SitanLi** [Esri/arcgis-maps-sdk-kotlin-samples#109]
# ArcGIS Android Issue Template

GitHub is **ONLY** used for issues pertaining to ArcGIS Maps SDK Kotlin Samples. Use [Esri Community](https://community.esri.com/t5/arcgis-runtime-sdk-for-android-questions/bd-p/arcgis-runtime-sdk-for-android-questions) for any general ArcGIS Maps SDK questions. 

Is this something you can [contribute](CONTRIBUTING.md)? Send a pull request! New Samples, bug fixes and documentation fixes are welcome.

Neither of the above? Submit an issue: 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by shubham7109** [comment]
`ImageTiledLayer` ([API ref](https://developers.arcgis.com/kotlin/api-reference/arcgis-maps-kotlin/com.arcgismaps.mapping.layers/-image-tiled-layer/index.html?query=sealed%20class%20ImageTiledLayer%20:%20ImageAdjustmentLayer))is the base class for layers that display cached maps. There are 4 inheritors you could use depending on your use case:
- `CustomTiledLayer` 
- `ArcGISTiledLayer`
- `ServiceImageTiledLayer`
- `WmtsLayer`

**Comment by shubham7109** [comment]
We have couple samples apps that creates a map using a tiled layer: 
- https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/tree/main/find-route-in-transport-network
- https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/tree/main/add-web-tiled-layer

**Comment by SitanLi** [comment]
ok&nbsp; thank you very much&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shubham ***@***.***&gt;; 
发送时间: 2023年6月6日(星期二) 凌晨1:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Esri/arcgis-maps-sdk-kotlin-samples] ImageTiledLayer is sealed class ? can I extends ? (Issue #109)





 
ImageTiledLayer (API ref)is the base class for layers that display cached maps. There are 4 inheritors you could use depending on your use case:
  
CustomTiledLayer
 
ArcGISTiledLayer
 
ServiceImageTiledLayer
 
WmtsLayer

**Comment by SitanLi** [comment]
I would like to inquire about a question. Before version 100.15.2, I could achieve offline caching by inheriting ImageTiledLayer to load my own tile data stored in the database. But in 200.1.0, ImageTiledLayer was a sealed class, and I can't do it anymore. I can only implement it through WebTiledLayer or ArcGISTiledLayer, right?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Esri/arcgis-maps-sdk-kotlin-samples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 凌晨1:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Esri/arcgis-maps-sdk-kotlin-samples] ImageTiledLayer is sealed class ? can I extends ? (Issue #109)





 
ImageTiledLayer (API ref)is the base class for layers that display cached maps. There are 4 inheritors you could use depending on your use case:
  
CustomTiledLayer
 
ArcGISTiledLayer
 
ServiceImageTiledLayer
 
WmtsLayer

**Comment by SitanLi** [comment]
Wow, I'm sorry. I just found out that Custom TiledLayer is an alternative solution. Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Esri/arcgis-maps-sdk-kotlin-samples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 凌晨1:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Esri/arcgis-maps-sdk-kotlin-samples] ImageTiledLayer is sealed class ? can I extends ? (Issue #109)





 
ImageTiledLayer (API ref)is the base class for layers that display cached maps. There are 4 inheritors you could use depending on your use case:
  
CustomTiledLayer
 
ArcGISTiledLayer
 
ServiceImageTiledLayer
 
WmtsLayer
