### ISSUE TITLE
The question about how to forbid map rotation

### ISSUE THREAD

**Issue by HaoYunyun** [Esri/arcgis-maps-sdk-kotlin-samples#188]
In ArcGIS Runtime SDK 100.15, can use mMapView.setOnTouchListener(new DefaultMapViewOnTouchListener(this, mMapView)  {
    @Override public boolean onRotate(MotionEvent event, double rotationAngle) {
        return false;
    }
})

But in 200，no similar method，so how to forbid map rotation

**Comment by JustKhit** [comment]
On 200.4.0 version, there is an option

` mapView.interactionOptions.apply {
     isRotateEnabled = false
}`
