### ISSUE TITLE
When reusing composable - error ObjectAlreadyOwnedException 

### ISSUE THREAD

**Issue by eugene-rsi-europe** [Esri/arcgis-maps-sdk-kotlin-samples#202]
https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/blob/6008ed17ec1e357fbc6f80b80b46452afd401163/show-callout/src/main/java/com/esri/arcgismaps/sample/showcallout/components/ComposeMapView.kt#L97

change this

```
DisposableEffect(lifecycleOwner) {
        lifecycleOwner.lifecycle.addObserver(mapView)
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(mapView)
        }
    }
```

To this

```
DisposableEffect(lifecycleOwner) {
        lifecycleOwner.lifecycle.addObserver(mapView)
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(mapView)
            mapView.map = null
        }
    }
```

**Comment by rchintapalli** [comment]
Thanks. Latest show-callout samples uses the Composable Mapview from our toolkit which handles the lifecycle management.

https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/blob/main/show-callout/src/main/java/com/esri/arcgismaps/sample/showcallout/screens/MainScreen.kt#L52
