### ISSUE TITLE
How to instantiated WebTiledLayer

### ISSUE THREAD

**Issue by winstone-su** [Esri/arcgis-maps-sdk-kotlin-samples#47]
WebTiledLayer is sealed class

**Comment by shubham7109** [comment]
@winstone-su `WebTiledLayer` is not part of the ArcGIS Maps SDK for Kotlin **Beta** release. The functionality will be enabled during the **final** release of ArcGIS Maps SDK for Kotlin.  Check out the beta [release notes](https://developers.arcgis.com/kotlin/release-notes/release-notes-for-200-0/)
